#  Jeu de Taquin (Sliding puzzle)

In [1]:
import numpy as np

## Algorithme de solvabilité du Taquin

```Python
    Algorithme GrilleTaquinSolvable
    """
    Argument :
    - grille : Une liste d'entier naturel de taille tailleCarre**2 (Ce n'est pas une liste de liste)
    - tailleCarre : un entier naturel supérieur à 2
    Le programme etudit la présence de l'invariant afin de determiner si le jeu possède un coefficient de dérangement
    pair ou impaire. Le coefficient est calculé en ajoutant 1 au coefficient pour chaque combinaison qui 
    s'effectue dans l'ordre exemple : Si 1 est avant 2 dans la liste alors le coefficient augmente de 1
    Cette fonction qui retourne un boolean True si la grille de taquin est solvable, sinon False.
    """
    
    Initialisation TableauCombinaison;
    Initialisation CoefficientDerangement;
    Pour tout nombre i compris entre 1 et tailleCarre^2 faire:
        Pour tout nombre j compris entre i+1 et tailleCarre^2 faire:
            TableauIntermediaire := [i,j]
            Si TableauIntermediaire n est pas contenu dans TableauCombinaison faire:
                Ajouter TableauIntermediaire à TableauCombinaison
            Fin si
        Fin pour tout
    Fin pour tout
    CoefficientDerangement:= 0;
    Initialisation indexSuperieur et indexInferieur; 
    Pour tout TableauIntermediaire contenu dans TableauCombinaison faire:
        indexSuperieur:= 0 
        indexInferieur:= 0
        Pour tout element k de la liste grille faire:
            Si l element au rang 0 du TableauIntermediaire est égale à k alors
                indexInferieur:= k
            Fin si
            Si l element au rang 1 du TableauIntermediaire est égale à k alors
                indexInferieur:= k
            Fin si
        Fin Pour tout;
        Si indexInferieur est inférieur à indexInferieur alors
            Ajoutez 1 à CoefficientDerangement 
        Fin Si
    Fin pour tout
    Si CoefficientDerangement est pair alors
        Retourner Vrai
    Sinon
        Retourner Faux
    Fin si
    
```

In [64]:
def GrilleTaquinSolvable(grille, tailleCarre):
    """
     Argument :
    - grille : Une liste d'entier naturel de taille tailleCarre**2 (Ce n'est pas une liste de liste)
    - tailleCarre : un entier naturel supérieur à 2
    Le programme etudit la présence de l'invariant afin de determiner si le jeu possède un coefficient de dérangement
    pair ou impaire. Le coefficient est calculé en ajoutant 1 au coefficient pour chaque combinaison qui 
    s'effectue dans l'ordre exemple : Si 1 est avant 2 dans la liste alors le coefficient augmente de 1
    Cette fonction qui retourne un boolean True si la grille de taquin est solvable, sinon False.
    """
    if type(grille[0]) == list:
        entendu = [item for sub in grille for item in sub]
    else:
        entendu = grille
    listCombinaison = []
    for i in range(1, tailleCarre**2):
        for j in range(i+1, tailleCarre**2):
            if not [i, j] in listCombinaison:
                listCombinaison.append([i, j])
    coefDerangement = 0
    for combi in listCombinaison:
        if entendu.index(combi[0]) < entendu.index(combi[1]):
            coefDerangement +=1
    if coefDerangement % 2 != 0:
        return True
    else:
        return False

### Grille 2x2

In [58]:
# Exemple de grille solvable
tailleCarre = 2
grille = [0, 2, 3, 1]
print("Grille : \n\n",np.array(grille).reshape((tailleCarre, tailleCarre)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable(grille, tailleCarre))

# Exemple de grille non solvable
grille = [1, 3, 2, 0]
print("\nGrille : \n\n",np.array(grille).reshape((tailleCarre, tailleCarre)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable(grille, tailleCarre))

Grille : 

 [[0 2]
 [3 1]]

Cette grille de Taquin est solvable ?  True

Grille : 

 [[1 3]
 [2 0]]

Cette grille de Taquin est solvable ?  False


### Grille 3x3

In [48]:
# Exemple de grille solvable
print("Grille : \n\n",np.array([0, 1, 2, 3, 4, 5, 8, 6, 7]).reshape((3, 3)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable([0, 1, 2, 3, 4, 5, 6, 7, 8], 3))

# Exemple de grille non solvable
print("\nGrille : \n\n",np.array([0, 1, 2, 3, 4, 5, 6, 8, 7]).reshape((3, 3)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable([0, 1, 2, 3, 4, 5, 6, 8, 7], 3))

Grille : 

 [[0 1 2]
 [3 4 5]
 [8 6 7]]

Cette grille de Taquin est solvable ?  False

Grille : 

 [[0 1 2]
 [3 4 5]
 [6 8 7]]

Cette grille de Taquin est solvable ?  True


### Grille 4x4

In [49]:
# Exemple de grille solvable
print("Grille : \n\n",np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).reshape((4, 4)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], 4))

# Exemple de grille non solvable
print("\nGrille : \n\n",np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 14]).reshape((4, 4)))
print("\nCette grille de Taquin est solvable ? ",GrilleTaquinSolvable([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 14], 4))

Grille : 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Cette grille de Taquin est solvable ?  True

Grille : 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 15 14]]

Cette grille de Taquin est solvable ?  False


## Parti résolution du jeu

### Mis en forme du jeu

In [63]:
def taquin(grille, tailleCarre, choix):
    
    def rules(position, grille, tailleCarre, position0) :
        if position//tailleCarre != position0//tailleCarre and position%tailleCarre != position0%tailleCarre :
            return -5
        elif (position<0) or (position>=tailleCarre**2) or (position//tailleCarre < 0) or (position//tailleCarre > tailleCarre):
            return -5
        else:
            base = np.copy(grille)
            temp = grille[position]
            grille[position0] = temp
            grille[position] = 0
            position0 = position
            return -1

    position0 = np.where(grille==0)[0][0]
    temp = 0
    if choix == 0 :
        temp = position0 + 1
    elif choix == 1:
        temp = position0 - 1
    elif choix == 2:
        temp = position0 + tailleCarre
    elif choix == 3:
        temp = position0 - tailleCarre
    r = rules(temp, grille, tailleCarre, position0)
    return grille, r   


### Définition de chaque noeud

In [18]:
class Edge:
    def __init__(self, state, cout, h, parent):
        self.h = h
        self.cout = cout
        self.state = "".join(map(str,state))
        self.parent = parent
    
    def getStateArray(self):
        return np.array([int(c) for c in self.state])
    
    def __lt__(self, OtherNode):
        return  self.h < OtherNode.h
    
    def __eq__(self, OtherNode):
        return self.state == OtherNode.state
    
    def show(self, tailleCarre):
        return (self.getStateArray()).reshape((tailleCarre, tailleCarre)) 
    
    def __str__(self):
            return self.state


### Fonction utile à l'algorithme A*

In [38]:
def manhattanDistance(g, tailleCarre):
    """
    La fonction de distance manhattan prend deux arguments :
    - tailleCarre est la taille de Grille (4 si grille 4x4)
    - Une grille de taquin dont la dimension est tailleCarre au carre
    Cette fonction verifie en premier lieu s'il y a des elements dans le mauvais ordre
    Puis s'il y en a, elle créer une liste de booléen permettant de connaitre par leur index
    les mauvais placements des tuilles du jeu
    Par la connaissances du mauvais placement, nous pouvons calculer la distance mannahtan de toutes les
    tuilles mal placées grace au calcul suivant :
        |i % tailleCarre - (Position de i) % tailleCarre| + | i // tailleCarre-(Position de i) // tailleCarre |
    et retourner leur somme.
    """ 
    base = [False if i == j else True for (i, j) in zip(g, range(tailleCarre**2))]
    return sum(abs(i%tailleCarre-(g[i]-1)%tailleCarre) + abs(i//tailleCarre-(g[i]-1)//tailleCarre) for i, val in enumerate(base) if val) 

def isNotExistClosed(grille, take):
    for i in take:
        if i==grille:
            return False
    return True

def isNotExistOpen(grille, take):
    for i, e in enumerate(take):
        if e==grille:
            if grille<e:
                return i
            return -2
    return -1

### Algorithme A*

```Python
    
   Algorithme A*
    """
    Argument :
    - grille : Une liste d'entier naturel de taille tailleCarre**2 (Ce n'est pas une liste de liste)
    - tailleCarre : un entier naturel supérieur strictement à 1
    Ne retourne rien
    Cet algorithme suit l'algorithme A*. C'est une recherche au travers d'un arbre de possibilité en utilisant l'heuristique manhattan qui favorise le suivi des branches pouvant mener une résolution plus rapide du jeu.
    Les listes Open, closed contiennent des objets :
        - Un noeud contient une grille, sa distance manhattan ainsi que la position du parent dans closed
    """
    Initialisation Open, closed, deux liste contenant les Noeuds
    Ajouter grille, sa distance Manhatan à Open 
    Tant que Open n est pas vide faire:
        x := grille ayant la plus petite distance manhatan 
        Retirer x de Open 
        Ajouter x à Closed
        Si la grille de x est égale à la grille final alors
            Reconstruction du chemin de grille à x
        Fin si
        Pour toutes les grilles y obtenu par les action possible de x faire:
            Si y n appartient pas à closed et que l action de x est possible faire:
                Si y appartient à Open et que sa distance manhantan est plus petit que l élément contenu dans Open ou y n appartient pas à Open faire
                    Ajoutez y à Open
                Fin si
            Fin si
        Fin pour tout
    Fin Tant que
    Fin Algorithme
        
```

In [62]:
def A_star(grille, tailleCarre):
    """
    Argument :
    - grille : Une liste d'entier naturel de taille tailleCarre**2 (Ce n'est pas une liste de liste)
    - tailleCarre : un entier naturel supérieur strictement à 1
    Ne retourne rien
    Cet algorithme suit l'algorithme A*. C'est une recherche au travers d'un arbre de possibilité en utilisant l'heuristique manhattan qui favorise le suivi des branches pouvant mener une résolution plus rapide du jeu.
    Les listes Open, closed contiennent des objets :
        - Un noeud contient une grille, sa distance manhattan ainsi que la position du parent dans closed
    """
    assert tailleCarre < 4 and tailleCarre > 1, "La tailleCarre du taquin est soit de 2 ou 3"
    assert tailleCarre**2 == len(grille), "La grille n'a pas la taille dite par tailleCarre"
    print("Base :\n",grille.reshape((tailleCarre, tailleCarre)))
    print("\nBut :\n",np.arange(tailleCarre**2).reshape((tailleCarre, tailleCarre)))
    Open = [Edge(grille, 0, manhattanDistance(grille, tailleCarre), None)]
    closed = []
    show = 0
    solvable = False
    print("\nLancement de l'algorithme... \n")
    while Open:
        indice = 0
        for i in range(1, len(Open)):
            if  Open[i] < Open[indice]:
                    indice = i
        x = Open[indice]
        closed.append(x)
        Open.pop(indice)
        if x.state == "".join(map(str,list(range(tailleCarre**2)))):
            solvable = True
            i = len(closed)-1
            s = []
            j = 0
            while i != None:
                s.append(str(closed[i].show(tailleCarre)))
                i = closed[i].parent
                j += 1
            s = s[::-1]
            print("\nNombre de cout nécéssaire : ", j, "\n")
            for i in range(len(s)-1):
                print(s[i]+ "-->\n")
            print(s[len(s)-1])
            break 
        for choix in range(4):
            grilleChoix, stop = taquin(x.getStateArray(), tailleCarre, choix)
            m = manhattanDistance(grilleChoix, tailleCarre)
            e = Edge(grilleChoix, x.cout + 1, m, len(closed)-1)
            if not stop == -5 and isNotExistClosed(e,  closed) :
                i = isNotExistOpen(e,  Open)
                if i >= 0:
                    Open[i] = e
                elif i ==-1:
                    Open.append(e)
        show += 1
    if not solvable :
        print("\n Le problème est non slovable, toutes les combinaisons ont été essayer..")

### Grille de commencement

In [42]:
"""
    Grille générer aléatoirement de taille 2x2 
"""
tailleCarre = 2
grille = np.arange(tailleCarre**2)
np.random.shuffle(grille)

In [156]:
"""
    Grille générer aléatoirement de taille 3x3 
"""
tailleCarre = 3
grille = np.arange(tailleCarre**2)
np.random.shuffle(grille)

In [157]:
"""
    Grille solvable en 3 x 3 
"""
grille = np.array([3, 0, 8, 6, 2, 1, 5, 4, 7])
tailleCarre = 3

In [59]:
"""
    Grille solvable en 3 x 3 
"""
grille = np.array([0, 2, 3, 1])
tailleCarre = 2

### Lancement du jeu

In [61]:
estSolvable = GrilleTaquinSolvable(grille.tolist(), tailleCarre)
print("La grille est solvable ? :",GrilleTaquinSolvable(grille.tolist(), tailleCarre))
if estSolvable :
    A_star(grille, tailleCarre)

La grille est solvable ? : True
Base :
 [[0 2]
 [3 1]]

But :
 [[0 1]
 [2 3]]

Lancement de l'algorithme... 

Grille Solvable

Nombre de cout nécéssaire :  5 

[[0 2]
 [3 1]]-->

[[2 0]
 [3 1]]-->

[[2 1]
 [3 0]]-->

[[2 1]
 [0 3]]-->

[[0 1]
 [2 3]]
